global:
  resolve_timeout: 30s

route:
  group_by: ['alertname']
  group_wait: 1s
  group_interval: 1s
  repeat_interval: 10s
  receiver: 'xmpp-webhook'

receivers:
  - name: 'xmpp-webhook'
    webhook_configs:
      - url: 'http://172.17.0.1:4321/prometheus'
